data:
  dataset1_path: '../data/dataset/dataset1' # path dataset root
  dataset2_path: '../data/dataset/dataset2' # path dataset root
  batch_size: 256

model:
  device: "cpu"
  skip_connection : true
  expansion : "up" # up or trans
  batch_normalization : false
  epochs: 5
  num_classes: 8
  early_stopping: false
  path : null # path to model checkpoint set null when training
optimizer:
  weight_decay: 0.0001
  lr: 0.01
